# Generated by Django 6.1 on 2026-09-12 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('medical_records', '0004_auditevent_prescription'),
        ('patients', '0004_patient_regime_and_relationship_deactivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ISSUED', 'Emitida'), ('VOIDED', 'Anulada')], max_length=20)),
                ('study_type', models.CharField(choices=[('LABORATORY', 'Laboratorio'), ('IMAGING', 'Gabinete'), ('HISTOPATHOLOGY', 'Histopatología'), ('OTHER', 'Otro')], max_length=20)),
                ('indications', models.TextField(blank=True, default='')),
                ('observations', models.TextField(blank=True, default='')),
                ('issued_at', models.DateTimeField()),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinical_encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_orders', to='medical_records.clinicalencounter')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_orders', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_orders', to='patients.patient')),
                ('previous_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_version', to='study_orders.studyorder')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='study_orders_voided', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'solicitud de estudio',
                'verbose_name_plural': 'solicitudes de estudio',
            },
        ),
        migrations.CreateModel(
            name='StudyOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('study_name', models.CharField(max_length=255)),
                ('specific_instructions', models.TextField(blank=True, default='')),
                ('study_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='study_orders.studyorder')),
            ],
            options={
                'verbose_name': 'estudio solicitado',
                'verbose_name_plural': 'estudios solicitados',
                'ordering': ['study_order', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='studyorder',
            index=models.Index(fields=['patient', 'issued_at'], name='study_order_patient_a6dce0_idx'),
        ),
        migrations.AddIndex(
            model_name='studyorder',
            index=models.Index(fields=['doctor', 'issued_at'], name='study_order_doctor__11ef2f_idx'),
        ),
        migrations.AddIndex(
            model_name='studyorder',
            index=models.Index(fields=['clinical_encounter'], name='study_order_clinica_06be0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='studyorder',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ISSUED', 'VOIDED'])), name='study_order_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='studyorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'VOIDED'), ('voided_at__isnull', False), ('voided_by__isnull', False)), models.Q(('status', 'ISSUED'), ('voided_at__isnull', True), ('voided_by__isnull', True)), _connector='OR'), name='study_order_voided_requires_trace'),
        ),
        migrations.AddConstraint(
            model_name='studyorder',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='study_order_version_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='studyorder',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('doctor', 'idempotency_key'), name='study_order_idempotency_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='studyorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='study_order_item_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='studyorderitem',
            constraint=models.UniqueConstraint(fields=('study_order', 'position'), name='study_order_item_position_unique'),
        ),
    ]
