# Generated by Django 6.1 on 2026-09-11 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0004_patient_regime_and_relationship_deactivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_history', models.TextField(blank=True, default='', verbose_name='antecedentes heredofamiliares')),
                ('personal_pathological_history', models.TextField(blank=True, default='', verbose_name='antecedentes personales patológicos')),
                ('personal_non_pathological_history', models.TextField(blank=True, default='', verbose_name='antecedentes personales no patológicos')),
                ('housing_history', models.TextField(blank=True, default='', verbose_name='vivienda')),
                ('gynecologic_obstetric_history', models.TextField(blank=True, default='', verbose_name='antecedentes gineco-obstétricos')),
                ('other_relevant_history', models.TextField(blank=True, default='', verbose_name='otros antecedentes relevantes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='medical_record', to='patients.patient')),
            ],
            options={
                'verbose_name': 'expediente clínico',
                'verbose_name_plural': 'expedientes clínicos',
            },
        ),
        migrations.CreateModel(
            name='ClinicalEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En progreso'), ('COMPLETED', 'Completada')], max_length=20)),
                ('reason_for_visit', models.TextField(blank=True, default='', verbose_name='motivo de consulta')),
                ('present_illness', models.TextField(blank=True, default='', verbose_name='padecimiento actual')),
                ('physical_exam', models.TextField(blank=True, default='', verbose_name='exploración física')),
                ('assessment', models.TextField(blank=True, default='', verbose_name='evaluación / diagnóstico')),
                ('plan', models.TextField(blank=True, default='', verbose_name='plan / indicaciones')),
                ('vital_signs', models.TextField(blank=True, default='', verbose_name='signos vitales')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='peso (kg)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='talla (cm)')),
                ('relevant_history', models.TextField(blank=True, default='', verbose_name='antecedentes relevantes')),
                ('studies', models.TextField(blank=True, default='', verbose_name='estudios')),
                ('observations', models.TextField(blank=True, default='', verbose_name='observaciones')),
                ('created_at', models.DateTimeField()),
                ('started_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_encounter', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_encounters', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'encuentro clínico',
                'verbose_name_plural': 'encuentros clínicos',
                'indexes': [models.Index(fields=['doctor', 'status'], name='medical_rec_doctor__80a6a5_idx'), models.Index(fields=['started_at'], name='medical_rec_started_bd9296_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['IN_PROGRESS', 'COMPLETED'])), name='clinical_encounter_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'COMPLETED')), models.Q(('completed_at__isnull', True), ('status', 'IN_PROGRESS')), _connector='OR'), name='clinical_encounter_completed_at_matches_status'), models.CheckConstraint(condition=models.Q(('started_at__gte', models.F('created_at'))), name='clinical_encounter_started_after_created'), models.CheckConstraint(condition=models.Q(('completed_at__isnull', True), ('completed_at__gte', models.F('started_at')), _connector='OR'), name='clinical_encounter_completed_after_started'), models.CheckConstraint(condition=models.Q(('weight_kg__isnull', True), ('weight_kg__gt', 0), _connector='OR'), name='clinical_encounter_weight_positive'), models.CheckConstraint(condition=models.Q(('height_cm__isnull', True), ('height_cm__gt', 0), _connector='OR'), name='clinical_encounter_height_positive')],
            },
        ),
    ]
