# Generated by Django 6.1 on 2026-09-11 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('medical_records', '0001_initial'),
        ('patients', '0004_patient_regime_and_relationship_deactivation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor_role', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('START_ENCOUNTER', 'Inicio de consulta'), ('SAVE_ENCOUNTER', 'Guardado de consulta'), ('COMPLETE_ENCOUNTER', 'Finalización de consulta'), ('READ_CLINICAL_ENCOUNTER', 'Lectura de encuentro clínico'), ('READ_MEDICAL_RECORD', 'Lectura de expediente'), ('READ_CLINICAL_HISTORY', 'Lectura de historial clínico'), ('CREATE_MEDICAL_RECORD', 'Creación de expediente'), ('UPDATE_MEDICAL_RECORD', 'Actualización de expediente')], max_length=30)),
                ('result', models.CharField(choices=[('SUCCESS', 'Éxito'), ('DENIED', 'Denegado'), ('REJECTED', 'Rechazado'), ('ERROR', 'Error')], max_length=10)),
                ('reason_code', models.CharField(blank=True, default='', max_length=60)),
                ('resource_type', models.CharField(choices=[('ClinicalEncounter', 'Encuentro clínico'), ('MedicalRecord', 'Expediente clínico'), ('ClinicalHistory', 'Historial clínico'), ('Appointment', 'Cita')], max_length=30)),
                ('resource_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_audit_events', to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='appointments.appointment')),
                ('clinical_encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medical_records.clinicalencounter')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='patients.patient')),
            ],
            options={
                'verbose_name': 'evento de auditoría clínica',
                'verbose_name_plural': 'eventos de auditoría clínica',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['patient', 'occurred_at'], name='medical_rec_patient_34511d_idx'), models.Index(fields=['actor', 'occurred_at'], name='medical_rec_actor_i_fd2a64_idx'), models.Index(fields=['action', 'occurred_at'], name='medical_rec_action_9d59bc_idx')],
            },
        ),
    ]
