# Generated by Django 6.1 on 2026-09-12 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_documents', '0001_initial'),
        ('medical_records', '0002_auditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='clinical_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clinical_documents.clinicaldocument'),
        ),
    ]
