# Generated by Django 6.1 on 2026-09-12 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0004_auditevent_prescription'),
        ('study_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='study_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='study_orders.studyorder'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('START_ENCOUNTER', 'Inicio de consulta'), ('SAVE_ENCOUNTER', 'Guardado de consulta'), ('COMPLETE_ENCOUNTER', 'Finalización de consulta'), ('READ_CLINICAL_ENCOUNTER', 'Lectura de encuentro clínico'), ('READ_MEDICAL_RECORD', 'Lectura de expediente'), ('READ_CLINICAL_HISTORY', 'Lectura de historial clínico'), ('CREATE_MEDICAL_RECORD', 'Creación de expediente'), ('UPDATE_MEDICAL_RECORD', 'Actualización de expediente'), ('ISSUE_PRESCRIPTION', 'Emisión de receta'), ('ISSUE_STUDY_ORDER', 'Emisión de solicitud de estudio'), ('VOID_PRESCRIPTION', 'Anulación de receta'), ('VOID_STUDY_ORDER', 'Anulación de solicitud de estudio'), ('UPLOAD_CLINICAL_DOCUMENT', 'Carga de documento clínico'), ('GENERATE_CLINICAL_DOCUMENT', 'Generación de documento clínico'), ('READ_CLINICAL_DOCUMENT', 'Lectura de documento clínico'), ('DOWNLOAD_CLINICAL_DOCUMENT', 'Descarga de documento clínico'), ('CREATE_DOCUMENT_VERSION', 'Nueva versión de documento clínico'), ('VOID_CLINICAL_DOCUMENT', 'Anulación de documento clínico')], max_length=30),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='resource_type',
            field=models.CharField(choices=[('ClinicalEncounter', 'Encuentro clínico'), ('MedicalRecord', 'Expediente clínico'), ('ClinicalHistory', 'Historial clínico'), ('Appointment', 'Cita'), ('Prescription', 'Receta'), ('StudyOrder', 'Solicitud de estudio'), ('ClinicalDocument', 'Documento clínico')], max_length=30),
        ),
    ]
