# Generated by Django 6.1 on 2026-09-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0005_auditevent_study_order_alter_auditevent_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('START_ENCOUNTER', 'Inicio de consulta'), ('SAVE_ENCOUNTER', 'Guardado de consulta'), ('COMPLETE_ENCOUNTER', 'Finalización de consulta'), ('READ_CLINICAL_ENCOUNTER', 'Lectura de encuentro clínico'), ('READ_MEDICAL_RECORD', 'Lectura de expediente'), ('READ_CLINICAL_HISTORY', 'Lectura de historial clínico'), ('CREATE_MEDICAL_RECORD', 'Creación de expediente'), ('UPDATE_MEDICAL_RECORD', 'Actualización de expediente'), ('ISSUE_PRESCRIPTION', 'Emisión de receta'), ('ISSUE_STUDY_ORDER', 'Emisión de solicitud de estudio'), ('VOID_PRESCRIPTION', 'Anulación de receta'), ('VOID_STUDY_ORDER', 'Anulación de solicitud de estudio'), ('UPLOAD_CLINICAL_DOCUMENT', 'Carga de documento clínico'), ('GENERATE_CLINICAL_DOCUMENT', 'Generación de documento clínico'), ('READ_CLINICAL_DOCUMENT', 'Lectura de documento clínico'), ('DOWNLOAD_CLINICAL_DOCUMENT', 'Descarga de documento clínico'), ('CREATE_DOCUMENT_VERSION', 'Nueva versión de documento clínico'), ('VOID_CLINICAL_DOCUMENT', 'Anulación de documento clínico'), ('LOGIN', 'Inicio de sesión'), ('MODIFY_PATIENT', 'Modificación de paciente'), ('CHANGE_PERMISSIONS', 'Cambio de permisos'), ('DISABLE_USER', 'Desactivación de usuario'), ('ADMIN_SENSITIVE_ACCESS', 'Acceso administrativo a información sensible')], max_length=30),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='resource_type',
            field=models.CharField(choices=[('ClinicalEncounter', 'Encuentro clínico'), ('MedicalRecord', 'Expediente clínico'), ('ClinicalHistory', 'Historial clínico'), ('Appointment', 'Cita'), ('Prescription', 'Receta'), ('StudyOrder', 'Solicitud de estudio'), ('ClinicalDocument', 'Documento clínico'), ('User', 'Usuario')], max_length=30),
        ),
    ]
