# Generated by Django 6.1 on 2026-09-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0006_alter_auditevent_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='resource_type',
            field=models.CharField(choices=[('ClinicalEncounter', 'Encuentro clínico'), ('MedicalRecord', 'Expediente clínico'), ('ClinicalHistory', 'Historial clínico'), ('Appointment', 'Cita'), ('Prescription', 'Receta'), ('StudyOrder', 'Solicitud de estudio'), ('ClinicalDocument', 'Documento clínico'), ('User', 'Usuario'), ('Patient', 'Paciente')], max_length=30),
        ),
    ]
