"""Domain error taxonomy for Agenda (docs/design/agenda-service-contracts.md
§9): Authorization, Availability, Hold, Appointment, Concurrency,
Idempotency. Views/API translate these to HTTP responses — they never leak
PostgreSQL/Django internals to the client."""


class AgendaError(Exception):
    """Base for every Agenda domain error."""


class NotAuthorized(AgendaError):
    """The acting user isn't authorized for this operation on this
    resource — deny by default (docs/design/agenda-permissions.md §2.3)."""


# --- Availability ----------------------------------------------------------


class AvailabilityError(AgendaError):
    pass


class DoctorClinicRequired(AvailabilityError):
    """No active DoctorClinic relationship for the doctor+clinic combination."""


class AvailabilityStartInPast(AvailabilityError):
    pass


class AvailabilityBeyondBookingHorizon(AvailabilityError):
    """Beyond the 6 calendar-month horizon (not a fixed day count)."""


class InvalidAvailabilityInterval(AvailabilityError):
    """start_time >= end_time, or otherwise malformed."""


class AvailabilityConflict(AvailabilityError):
    """Overlaps another active Availability for the same doctor (any
    clinic) — docs/design/availability-rules.md §10/§11."""


class AvailabilityNotFound(AvailabilityError):
    pass


class AvailabilityHasAppointments(AvailabilityError):
    """Blocks deactivation — any occupying appointment at all."""


class AvailabilityHasIncompatibleAppointments(AvailabilityError):
    """Blocks modification — the new interval would no longer fully
    contain an existing occupying appointment (docs/design/
    availability-rules.md §19; docs/design/agenda-service-contracts.md
    §5.2, corrected 2026-09-10)."""


class InvalidSlot(AvailabilityError):
    """The requested interval doesn't correspond to a slot boundary
    generated by an active Availability (wrong alignment/duration)."""


# --- Booking (shared between Hold and Appointment) --------------------------


class SlotUnavailable(AgendaError):
    """The interval is occupied by a conflicting Appointment."""


class BookingWindowExpired(AgendaError):
    """More than 30 minutes have passed since the slot's start
    (docs/phases/phase-2-agenda.md §6.3/§9)."""


# --- Hold --------------------------------------------------------------------


class HoldError(AgendaError):
    pass


class HoldAlreadyExists(HoldError):
    """The actor already holds another ACTIVE, unexpired slot — must
    release it first (one hold per user)."""


class HoldConflict(HoldError):
    """Another user already holds this exact slot."""


class HoldNotFound(HoldError):
    pass


class HoldNotOwned(HoldError):
    pass


class HoldNotActive(HoldError):
    pass


class HoldExpired(HoldError):
    """Used when consuming a hold that expired between validation steps."""


# --- Appointment ---------------------------------------------------------


class AppointmentError(AgendaError):
    pass


class AppointmentConflict(AppointmentError):
    """Lost a race against a concurrent booking for the same interval —
    surfaced from a PostgreSQL ExclusionConstraint violation."""


class InvalidPatient(AppointmentError):
    """The named patient isn't a valid target for this actor to book for
    (docs/design/agenda-permissions.md §9): not the patient themself, not
    a patient with an ACTIVE ResponsiblePatientRelationship to the acting
    responsible, or not an active Patient record at all."""


class InvalidDoctorClinic(AppointmentError):
    """Either the doctor/clinic supplied by the caller don't match the
    hold's own doctor/clinic (docs/design/agenda-api-contracts.md §18 —
    the backend never trusts client-supplied doctor_id/clinic_id over the
    hold), or — for reschedule — there's no active DoctorClinic between
    the appointment's (frozen) doctor and the requested new clinic."""


class AppointmentNotFound(AppointmentError):
    pass


class AppointmentNotCancellable(AppointmentError):
    """Not SCHEDULED, or already started (docs/design/
    agenda-service-contracts.md §7.2)."""


class AppointmentAlreadyCancelled(AppointmentError):
    pass


class AppointmentNotReschedulable(AppointmentError):
    """Not SCHEDULED, or already started (docs/design/
    agenda-service-contracts.md §7.3)."""


class DurationIncompatible(AppointmentError):
    """The appointment's frozen `duration_minutes` doesn't match the
    target clinic's slot grid — the frozen duration can never stretch or
    shrink to fit a new consultorio (docs/design/agenda-service-contracts.md
    §7.3)."""


class AppointmentNotStartable(AppointmentError):
    """Not SCHEDULED (docs/design/agenda-service-contracts.md §7.4)."""


class AppointmentNotCompletable(AppointmentError):
    """Not IN_CONSULTATION (docs/design/agenda-service-contracts.md §7.5)."""


class NoShowNotAllowed(AppointmentError):
    """Not SCHEDULED, or fewer than 1 minute have passed since the
    scheduled start (docs/design/agenda-service-contracts.md §7.6)."""


# --- Idempotency -----------------------------------------------------------


class IdempotencyError(AgendaError):
    pass


class IdempotencyKeyConflict(IdempotencyError):
    """The same actor+idempotency_key was reused for a different logical
    operation (docs/design/agenda-service-contracts.md §8 /
    docs/design/agenda-api-contracts.md §15)."""
