# Generated by Django 6.1 on 2026-09-01 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'consultorio',
                'verbose_name_plural': 'consultorios',
            },
        ),
        migrations.CreateModel(
            name='DoctorClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_relationships', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_relationships', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'relación médico-consultorio',
                'verbose_name_plural': 'relaciones médico-consultorio',
                'constraints': [models.UniqueConstraint(fields=('doctor', 'clinic'), name='unique_doctor_clinic')],
            },
        ),
    ]
