# Generated by Django 6.1 on 2026-09-10 00:07

import clinics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='timezone',
            field=models.CharField(default='America/Mexico_City', max_length=64, validators=[clinics.models.validate_timezone], verbose_name='zona horaria'),
        ),
        migrations.AddField(
            model_name='doctorclinic',
            name='appointment_duration_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='duración de citas (minutos)'),
        ),
    ]
