# Generated by Django 6.1 on 2026-09-12 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('medical_records', '0002_auditevent'),
        ('patients', '0004_patient_regime_and_relationship_deactivation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('LABORATORY', 'Laboratorio'), ('IMAGING', 'Gabinete'), ('HISTOPATHOLOGY', 'Histopatología'), ('PHOTOGRAPH', 'Fotografía'), ('PRESCRIPTION', 'Receta'), ('INSTRUCTIONS', 'Indicaciones'), ('STUDY_ORDER', 'Solicitud de estudio'), ('OTHER', 'Otro')], max_length=20)),
                ('origin', models.CharField(choices=[('UPLOADED', 'Subido'), ('GENERATED', 'Generado')], max_length=20)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'Activo'), ('VOIDED', 'Anulado')], max_length=20, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, default='')),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_current_version', models.BooleanField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_documents', to='appointments.appointment')),
                ('clinical_encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_documents', to='medical_records.clinicalencounter')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_documents_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_documents', to='patients.patient')),
            ],
            options={
                'verbose_name': 'documento clínico',
                'verbose_name_plural': 'documentos clínicos',
            },
        ),
    ]
