# Generated by Django 6.1 on 2026-09-12 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical_documents', '0002_initial'),
        ('study_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaldocument',
            name='study_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_documents', to='study_orders.studyorder'),
        ),
        migrations.AddIndex(
            model_name='clinicaldocument',
            index=models.Index(fields=['patient', 'created_at'], name='clinical_do_patient_195f84_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaldocument',
            index=models.Index(fields=['patient', 'document_type', 'created_at'], name='clinical_do_patient_d4ee47_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaldocument',
            index=models.Index(fields=['appointment'], name='clinical_do_appoint_7bfd94_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaldocument',
            index=models.Index(fields=['clinical_encounter'], name='clinical_do_clinica_5e857f_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinicaldocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('prescription__isnull', False), ('study_order__isnull', False), _connector='OR'), ('status__isnull', True)), models.Q(('prescription__isnull', True), ('study_order__isnull', True), ('status__in', ['ACTIVE', 'VOIDED'])), _connector='OR'), name='clinicaldocument_status_matches_backing'),
        ),
        migrations.AddConstraint(
            model_name='clinicaldocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'VOIDED'), ('voided_at__isnull', False)), models.Q(('status', 'VOIDED'), _negated=True), _connector='OR'), name='clinicaldocument_voided_requires_trace'),
        ),
        migrations.AddConstraint(
            model_name='clinicaldocument',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='clinicaldocument_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='clinicaldocument',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__isnull', True), ('version_number__gte', 1), _connector='OR'), name='clinicaldocument_version_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='clinicaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(('origin', 'GENERATED')), fields=('prescription',), name='clinicaldocument_one_generated_per_prescription'),
        ),
        migrations.AddConstraint(
            model_name='clinicaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(('origin', 'GENERATED')), fields=('study_order',), name='clinicaldocument_one_generated_per_study_order'),
        ),
    ]
