# Generated by Django 6.1 on 2026-09-12 02:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinical_documents', '0003_initial'),
        ('medical_records', '0005_auditevent_study_order_alter_auditevent_action_and_more'),
        ('patients', '0004_patient_regime_and_relationship_deactivation'),
        ('prescriptions', '0001_initial'),
        ('study_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clinicaldocument',
            name='clinicaldocument_status_matches_backing',
        ),
        migrations.AddConstraint(
            model_name='clinicaldocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('prescription__isnull', False), ('study_order__isnull', False), _connector='OR'), ('status__isnull', True)), models.Q(('prescription__isnull', True), ('study_order__isnull', True), ('status__isnull', False), ('status__in', ['ACTIVE', 'VOIDED'])), _connector='OR'), name='clinicaldocument_status_matches_backing'),
        ),
    ]
