# Generated by Django 6.1 on 2026-09-01 23:59

import accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email del prospecto')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('USED', 'Utilizada'), ('EXPIRED', 'Expirada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'invitación',
                'verbose_name_plural': 'invitaciones',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='nombre(s)')),
                ('last_name_paterno', models.CharField(max_length=100, verbose_name='apellido paterno')),
                ('last_name_materno', models.CharField(blank=True, max_length=100, verbose_name='apellido materno')),
                ('birth_date', models.DateField(verbose_name='fecha de nacimiento')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono celular')),
                ('alternative_phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono alternativo')),
                ('street', models.CharField(blank=True, max_length=150, verbose_name='calle')),
                ('exterior_number', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='colonia')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='código postal')),
                ('municipality', models.CharField(blank=True, max_length=100, verbose_name='municipio/alcaldía')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='estado')),
                ('country', models.CharField(blank=True, default='México', max_length=100, verbose_name='país')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
