# Generated by Django 6.1 on 2026-09-21 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_invitation_invitation_used_at_requires_used_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('PRIVACY_NOTICE', 'Aviso de privacidad'), ('TERMS_AND_CONDITIONS', 'Términos y condiciones')], max_length=25)),
                ('policy_version', models.CharField(max_length=20)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'aceptación de documento de plataforma',
                'verbose_name_plural': 'aceptaciones de documentos de plataforma',
                'indexes': [models.Index(fields=['user', 'policy_type'], name='accounts_po_user_id_b5d732_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'policy_type', 'policy_version'), name='policyacceptance_user_type_version_unique')],
            },
        ),
    ]
