# Generated by Django 6.1 on 2026-09-12 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('medical_records', '0003_auditevent_clinical_document'),
        ('patients', '0004_patient_regime_and_relationship_deactivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ISSUED', 'Emitida'), ('VOIDED', 'Anulada')], max_length=20)),
                ('issued_at', models.DateTimeField()),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinical_encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='medical_records.clinicalencounter')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.patient')),
                ('previous_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_version', to='prescriptions.prescription')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_voided', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'receta',
                'verbose_name_plural': 'recetas',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('medication_name', models.CharField(max_length=255)),
                ('presentation', models.CharField(blank=True, default='', max_length=255)),
                ('dose', models.CharField(max_length=100)),
                ('dose_unit', models.CharField(blank=True, default='', max_length=50)),
                ('route', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(blank=True, default='', max_length=100)),
                ('instructions', models.TextField(blank=True, default='')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'medicamento de receta',
                'verbose_name_plural': 'medicamentos de receta',
                'ordering': ['prescription', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'issued_at'], name='prescriptio_patient_b46c63_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor', 'issued_at'], name='prescriptio_doctor__8715c1_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['clinical_encounter'], name='prescriptio_clinica_ca8b5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ISSUED', 'VOIDED'])), name='prescription_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'VOIDED'), ('voided_at__isnull', False), ('voided_by__isnull', False)), models.Q(('status', 'ISSUED'), ('voided_at__isnull', True), ('voided_by__isnull', True)), _connector='OR'), name='prescription_voided_requires_trace'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='prescription_version_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('doctor', 'idempotency_key'), name='prescription_idempotency_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionitem',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='prescription_item_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionitem',
            constraint=models.UniqueConstraint(fields=('prescription', 'position'), name='prescription_item_position_unique'),
        ),
    ]
