# Generated by Django 6.1 on 2026-09-10 00:10

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_clinic_timezone_and_more'),
        ('doctors', '0001_initial'),
        ('patients', '0004_patient_regime_and_relationship_deactivation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Required for ExclusionConstraint to use RangeOperators.EQUAL on
        # plain (non-range) columns like doctor_id/clinic_id below.
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('start_time', models.TimeField(verbose_name='hora de inicio')),
                ('end_time', models.TimeField(verbose_name='hora de fin')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('period', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='duración (minutos)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availabilities', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availabilities', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'disponibilidad',
                'verbose_name_plural': 'disponibilidades',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('period', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='duración (minutos)')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programada'), ('IN_CONSULTATION', 'En consulta'), ('COMPLETED', 'Atendida'), ('CANCELLED', 'Cancelada'), ('NO_SHOW', 'No se presentó')], max_length=20)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, choices=[('PATIENT_REQUEST', 'Solicitud del paciente'), ('RESPONSIBLE_REQUEST', 'Solicitud del responsable'), ('DOCTOR_REQUEST', 'Solicitud del médico'), ('CLINIC_REQUEST', 'Solicitud del consultorio'), ('OTHER', 'Otro')], max_length=20)),
                ('no_show_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments_cancelled', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinics.clinic')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments_completed', to='doctors.doctor')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctors.doctor')),
                ('no_show_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments_marked_no_show', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments_started', to='doctors.doctor')),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.availability')),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
            },
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('period', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('EXPIRED', 'Expirado'), ('RELEASED', 'Liberado'), ('CONSUMED', 'Consumido')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='appointments.availability')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='doctors.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_holds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bloqueo temporal',
                'verbose_name_plural': 'bloqueos temporales',
            },
        ),
        migrations.CreateModel(
            name='AppointmentRescheduleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_date', models.DateField()),
                ('old_start_at', models.DateTimeField()),
                ('old_end_at', models.DateTimeField()),
                ('new_date', models.DateField()),
                ('new_start_at', models.DateTimeField()),
                ('new_end_at', models.DateTimeField()),
                ('rescheduled_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('PATIENT_REQUEST', 'Solicitud del paciente'), ('RESPONSIBLE_REQUEST', 'Solicitud del responsable'), ('DOCTOR_REQUEST', 'Solicitud del médico'), ('CLINIC_REQUEST', 'Solicitud del consultorio'), ('OTHER', 'Otro')], max_length=20)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_history', to='appointments.appointment')),
                ('new_clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clinics.clinic')),
                ('old_clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clinics.clinic')),
                ('rescheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historial de reprogramación',
                'verbose_name_plural': 'historial de reprogramaciones',
                'ordering': ['-rescheduled_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('rescheduled_by', 'idempotency_key'), name='reschedule_idempotency_key_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='availability_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='availability_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_active', True)), expressions=[('period', '&&'), ('doctor', '=')], name='availability_doctor_no_overlap'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['SCHEDULED', 'IN_CONSULTATION', 'COMPLETED', 'CANCELLED', 'NO_SHOW'])), name='appointment_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='appointment_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CANCELLED'), _negated=True), models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), models.Q(('cancellation_reason', ''), _negated=True)), _connector='OR'), name='appointment_cancelled_requires_trace'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'NO_SHOW'), _negated=True), models.Q(('no_show_at__isnull', False), ('no_show_by__isnull', False)), _connector='OR'), name='appointment_no_show_requires_trace'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('created_by', 'idempotency_key'), name='appointment_idempotency_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['SCHEDULED', 'IN_CONSULTATION', 'COMPLETED'])), expressions=[('period', '&&'), ('doctor', '=')], name='appointment_doctor_no_overlap'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['SCHEDULED', 'IN_CONSULTATION', 'COMPLETED'])), expressions=[('period', '&&'), ('clinic', '=')], name='appointment_clinic_no_overlap'),
        ),
        migrations.AddConstraint(
            model_name='hold',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'EXPIRED', 'RELEASED', 'CONSUMED'])), name='hold_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='hold',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('user',), name='hold_one_active_per_user'),
        ),
        migrations.AddConstraint(
            model_name='hold',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'ACTIVE')), expressions=[('period', '&&'), ('doctor', '='), ('clinic', '=')], name='hold_active_no_doctor_clinic_overlap'),
        ),
    ]
