# Generated by Django 6.1 on 2026-09-01 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(blank=True, max_length=18, verbose_name='CURP')),
                ('nationality', models.CharField(blank=True, default='Mexicana', max_length=100, verbose_name='nacionalidad')),
                ('sex', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=1, verbose_name='sexo')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150, verbose_name='nombre del contacto de emergencia')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono del contacto de emergencia')),
                ('blood_type', models.CharField(blank=True, max_length=5, verbose_name='tipo sanguíneo')),
                ('allergies', models.TextField(blank=True, verbose_name='alergias')),
                ('chronic_conditions', models.TextField(blank=True, verbose_name='enfermedades crónicas')),
                ('current_medications', models.TextField(blank=True, verbose_name='medicamentos actuales')),
                ('surgical_history', models.TextField(blank=True, verbose_name='antecedentes quirúrgicos')),
                ('relevant_hospitalizations', models.TextField(blank=True, verbose_name='hospitalizaciones relevantes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='patient_profile', to='accounts.person')),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_contact', models.CharField(blank=True, max_length=150, verbose_name='contacto alternativo')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_profile', to='accounts.person')),
            ],
            options={
                'verbose_name': 'responsable',
                'verbose_name_plural': 'responsables',
            },
        ),
        migrations.CreateModel(
            name='DoctorPatientRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('TRATANTE', 'Médico tratante'), ('SUSTITUTO', 'Médico sustituto'), ('OTRO', 'Otro')], default='TRATANTE', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_relationships', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_relationships', to='patients.patient')),
            ],
            options={
                'verbose_name': 'relación médico-paciente',
                'verbose_name_plural': 'relaciones médico-paciente',
                'constraints': [models.UniqueConstraint(fields=('doctor', 'patient'), name='unique_doctor_patient')],
            },
        ),
        migrations.CreateModel(
            name='ResponsiblePatientRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('MADRE', 'Madre'), ('PADRE', 'Padre'), ('TUTOR_LEGAL', 'Tutor legal'), ('FAMILIAR', 'Familiar'), ('CUIDADOR', 'Cuidador'), ('OTRO', 'Otro')], max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_relationships', to='patients.patient')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_relationships', to='patients.responsible')),
            ],
            options={
                'verbose_name': 'relación responsable-paciente',
                'verbose_name_plural': 'relaciones responsable-paciente',
                'constraints': [models.UniqueConstraint(fields=('responsible', 'patient'), name='unique_responsible_patient')],
            },
        ),
    ]
