# Generated by Django 6.1 on 2026-09-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsiblepatientrelationship',
            name='is_active',
        ),
        migrations.AddField(
            model_name='responsiblepatientrelationship',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de aprobación'), ('ACTIVE', 'Vigente'), ('INACTIVE', 'Desactivada')], default='ACTIVE', max_length=10),
        ),
    ]
