# Generated by Django 6.1 on 2026-09-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_responsiblepatientrelationship_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsiblepatientrelationship',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de aprobación'), ('ACTIVE', 'Vigente'), ('INACTIVE', 'Desactivada')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='responsiblepatientrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'ACTIVE', 'INACTIVE'])), name='responsiblepatientrelationship_status_valid'),
        ),
    ]
