# Generated by Django 6.1 on 2026-09-16 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinics', '0002_clinic_timezone_and_more'),
        ('doctors', '0001_initial'),
        ('patients', '0004_patient_regime_and_relationship_deactivation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('padecimiento', models.TextField(blank=True, default='')),
                ('descripcion', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('NUEVA', 'Nueva'), ('CONVERTIDA', 'Convertida')], default='NUEVA', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='care_request', to='appointments.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_requests', to='clinics.clinic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_requests_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_requests', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_requests', to='patients.patient')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='care_requests', to='patients.responsible')),
            ],
            options={
                'verbose_name': 'solicitud de atención',
                'verbose_name_plural': 'solicitudes de atención',
                'indexes': [models.Index(fields=['patient', 'created_at'], name='care_reques_patient_70c8c9_idx'), models.Index(fields=['doctor', 'created_at'], name='care_reques_doctor__70a88f_idx'), models.Index(fields=['created_by', 'created_at'], name='care_reques_created_5f5619_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['NUEVA', 'CONVERTIDA'])), name='care_request_status_valid'), models.CheckConstraint(condition=models.Q(('start_at__lt', models.F('end_at'))), name='care_request_start_before_end'), models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('created_by', 'idempotency_key'), name='care_request_idempotency_key_unique')],
            },
        ),
    ]
