# Generated by Django 6.1 on 2026-09-18 16:36

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('care_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carerequest',
            name='clinical_document_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveBigIntegerField(), blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='carerequest',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='appointments.appointment'),
        ),
    ]
