# Generated by Django 6.1 on 2026-09-21 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_days', models.PositiveSmallIntegerField(verbose_name='días de anticipación')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ventana de recordatorio',
                'verbose_name_plural': 'ventanas de recordatorio',
                'ordering': ['-offset_days'],
                'constraints': [models.UniqueConstraint(fields=('offset_days',), name='reminderwindow_offset_days_unique'), models.CheckConstraint(condition=models.Q(('offset_days__gt', 0)), name='reminderwindow_offset_days_positive')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('REGISTRATION_INVITATION', 'Invitación de registro'), ('EMAIL_VERIFICATION', 'Verificación de correo'), ('PASSWORD_RECOVERY', 'Recuperación de contraseña'), ('APPOINTMENT_CREATED', 'Cita creada'), ('APPOINTMENT_MODIFIED', 'Cita modificada'), ('APPOINTMENT_CANCELLED', 'Cita cancelada'), ('APPOINTMENT_REMINDER', 'Recordatorio de cita')], max_length=30)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email')], default='EMAIL', max_length=10)),
                ('recipient_address', models.EmailField(max_length=254, verbose_name='dirección de envío')),
                ('resource_type', models.CharField(blank=True, choices=[('User', 'Usuario'), ('Appointment', 'Cita')], max_length=20)),
                ('resource_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(verbose_name='momento previsto de procesamiento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENDING', 'Enviando'), ('SENT', 'Enviada'), ('FAILED', 'Fallida'), ('CANCELLED', 'Cancelada')], max_length=10)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=255)),
                ('reason_code', models.CharField(blank=True, default='', max_length=60)),
                ('dedupe_key', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'indexes': [models.Index(fields=['scheduled_for', 'status'], name='notificatio_schedul_6d53f3_idx'), models.Index(fields=['recipient_user', 'created_at'], name='notificatio_recipie_a86600_idx'), models.Index(fields=['resource_type', 'resource_id'], name='notificatio_resourc_b66932_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('dedupe_key',), name='notification_dedupe_key_unique')],
            },
        ),
    ]
